### ISSUE TITLE
Unmovable items issue

### ISSUE THREAD

**Issue by KirillovPavel** [simulton/QSchematic#43]
Items are still movable after pItem->setMovable(false); I assumed, that you forgot to check movability in Scene::mouseMoveEvent().
This fix worked fine for me:
![image](https://github.com/simulton/QSchematic/assets/52327898/2668358d-60b1-4b8e-b243-1791edcc4227)

**Comment by Tectu** [comment]
That is correct - Thank you! :)

**Comment by KirillovPavel** [comment]
Hi! I forgot about mouseReleaseEvent(the same problem). My bad :)
