### ISSUE TITLE
Could you please explain what is GDS and GDPS for me and the location of the Serialize.h?Thank you very much!

### ISSUE THREAD

**Issue by gxygrenn** [simulton/QSchematic#5]
Such as the title

**Comment by Tectu** [comment]
Hi,
GPDS is a general purpose data serializer. It's being used to provide serialization support to QSchematic (so you can save and load your schematic to/from XML). You can find more information here:  https://gpds.simulton.com
It's being included into QSchematic as a git submodule. The official GPDS repository is located here: https://github.com/simulton/GPDS

**Comment by gxygrenn** [comment]
thanks a lot
