### ISSUE TITLE
ninja: error: CMakeFiles/impl-Debug.ninja:675: multiple rules generate qschematic/Debug/qschematicd.lib

### ISSUE THREAD

**Issue by aboelens** [simulton/QSchematic#50]
Building QSchematic on windows 10 I get the error message:

ninja: error: CMakeFiles/impl-Debug.ninja:675: multiple rules generate qschematic/Debug/qschematicd.lib

This is due to the static and shared library having the same name. Either removing the shared or static target from the CMakeList.txt gets rid of the error message.

**Comment by Tectu** [comment]
Quick question: Is that using Visual Studio?

**Comment by aboelens** [comment]
Hi Joel,

That is building from PowerShell.

Met vriendelijke groet / Kind regards,
--
Arnout Boelens
Principal Researcher Thermal Processes
R&D - Rolling, Finishing & Measurement
T: +31 (0) 251 495 136




Sensitivity: general

**Comment by Tectu** [comment]
This problem has been popping up on the Windows side before. I'll get that fixed but that might take a couple of days (definitely not before the weekend).

I suggest that you remove the corresponding CMake `add_library()` call to either the static or the shared library until we've fixed this in the upstream repository.

**Comment by aboelens** [comment]
Thanks! Will do

**Comment by Tectu** [comment]
This should now be fixed in the current master branch. Can you please check?

Note that you'll have to manually supply the correspondingly updated version of GPDS which also suffered from this problem.
See https://github.com/simulton/gpds/issues/16
