### ISSUE TITLE
  add_library cannot create ALIAS target "gpds::gpds-shared" because target   "gpds-shared" does not already exist.

### ISSUE THREAD

**Issue by aboelens** [simulton/QSchematic#53]
Hi Joel,

Sorry for the delay, but I finally got around testing the updated version. Unfortunately, I get the error:

CMake Error at qschematic/external.cmake:22 (add_library):
  add_library cannot create ALIAS target "gpds::gpds-shared" because target
  "gpds-shared" does not already exist.
Call Stack (most recent call first):
  qschematic/CMakeLists.txt:2 (include)

I did not manually install gpds. However, GPDS version 1.8.1 is fetched, which should have the bug fix. Am I missing something?

Thanks,

Arnout

**Comment by Tectu** [comment]
Hmm.... that issue most likely arises at line 21, 22 in `/qschematic/external.cmake`:
https://github.com/simulton/QSchematic/blob/4bcfa11993d6c55e1ba959feaafd833a522f66f0/qschematic/external.cmake#L22

Does everything work out-of-the-box if you comment that out?

**Comment by aboelens** [comment]
Yes, I just commented out line 22 and everything works out of the box.

**Comment by bjornstromberg** [comment]
> Hmm.... that issue most likely arises at line 21, 22 in `/qschematic/external.cmake`:
> 
> https://github.com/simulton/QSchematic/blob/4bcfa11993d6c55e1ba959feaafd833a522f66f0/qschematic/external.cmake#L22
> 
> Does everything work out-of-the-box if you comment that out?

yep those should not be there, they should be created by gpds.  removing them, and moving them to gpds in patches in  #63

**Comment by Tectu** [comment]
I consider this to be fixed.
