### ISSUE TITLE
`requires` error during compilation

### ISSUE THREAD

**Issue by LIU-Yinyi** [simulton/QSchematic#54]
When I built the project following the document, the error as follows was triggered. My GCC version is 9.4.0 and it should support C++17 and C++20 according to the official documentation. Other mentioned dependencies such as QT5.15 and GPDS have already been installed. `requires` seems like a feature since C++20. I tried modifying the `CMakeLists.txt` within `qschematic` to adapt to C++20 but this error still existed. Could you advise what action I should further do to solve this problem? Thank you. 

```bash
/dir/qt/qschematic/build/_deps/gpds-src/lib/include/gpds/serialize.hpp: In function ‘std::pair<bool, std::__cxx11::basic_string<char> > gpds::to_stream(std::ostream&, const Object&, std::string_view)’:
/dir/qt/qschematic/build/_deps/gpds-src/lib/include/gpds/serialize.hpp:49:23: error: ‘requires’ was not declared in this scope
   49 |         if constexpr (requires { obj.to_container(); })
      |                       ^~~~~~~~
/dir/qt/qschematic/build/_deps/gpds-src/lib/include/gpds/serialize.hpp:49:31: error: expected ‘)’ before ‘{’ token
   49 |         if constexpr (requires { obj.to_container(); })
      |                      ~        ^~
      |                               )
/dir/qt/qschematic/build/_deps/gpds-src/lib/include/gpds/serialize.hpp: In function ‘std::pair<bool, std::__cxx11::basic_string<char> > gpds::from_stream(std::istream&, Object&, std::string_view)’:
/dir/qt/qschematic/build/_deps/gpds-src/lib/include/gpds/serialize.hpp:118:23: error: ‘requires’ was not declared in this scope
  118 |         if constexpr (requires{ obj.from_container(gpds::container{}); }) {
      |                       ^~~~~~~~
/dir/qt/qschematic/build/_deps/gpds-src/lib/include/gpds/serialize.hpp:118:31: error: expected ‘)’ before ‘{’ token
  118 |         if constexpr (requires{ obj.from_container(gpds::container{}); }) {
      |                      ~        ^
      |                               )
make[2]: *** [qschematic/CMakeFiles/qschematic-shared.dir/build.make:76: qschematic/CMakeFiles/qschematic-shared.dir/qschematic-shared_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:293: qschematic/CMakeFiles/qschematic-shared.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by Tectu** [comment]
The compilation error(s) you're getting are definitely only related to the GPDS dependency (https://github.com/simulton/gpds).
Could you please share the version of GPDS you're using and which compiler you're using?

On a side note: I'll update the QSchematic readme to reflect the need for a C++20 compiler.

**Comment by Tectu** [comment]
> It seems that no explicit definition about C++ standard version in the `CMakeLists.txt` of [GPDS](https://github.com/simulton/gpds) project.

It's set as part of `target_set_properties()` here: https://github.com/simulton/gpds/blob/42f7b76a42fdc7068ca779c6f5bed1593e08e1dc/lib/CMakeLists.txt#L48
This transitively makes it to consuming projects (such as QSchematic).
Therefore, consuming GPDS `1.8.1` will automatically set C++20 as the required standard in the QSchematic targets (via the generated `gpds-targets.cmake` when consuming a GPDS installation and just via regular target properties when consuming a non-installed version).

Can you tell us exactly which compiler you're using?

**Comment by Tectu** [comment]
AFAIK GCC only supports concepts starting with version 10: https://en.cppreference.com/w/cpp/compiler_support
